// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a396c170ba4b6a7f45b20fccbdba0d2b81cc8833/pouchdb/pouchdb.d.ts
declare module 'pouchdb' {
    const plugin: PouchDB.Static;
    export = plugin;
}
